- name: check ~/.my.cnf
  stat:
    path: ~/.my.cnf
  register: mysql_root_password

- name: get temp password
  shell: "grep -o 'root@localhost:.*' /var/log/mysql/error.log | awk -F'root@localhost: ' '{print $2}'"
  register: mysql_temp_password
  when: mysql_root_password.stat.exists == false

# ansible で mysql_usre を使えるように
- name: dest ~/.tmp.my.cnf
  template:
    src: tmp.my.cnf.j2
    dest: /root/.tmp.my.cnf
    mode: 0600
  when: mysql_root_password.stat.exists == false

- name: change password policy
  shell: mysql --defaults-file=/root/.tmp.my.cnf -e "SET GLOBAL validate_password_policy=LOW;SET GLOBAL validate_password_length=4;"
  when: mysql_root_password.stat.exists == false

- name: change root password
  shell: mysql --defaults-file=/root/.tmp.my.cnf -e "SET PASSWORD FOR root@localhost=PASSWORD('{{ database_root_password }}')"
  when: mysql_root_password.stat.exists == false

# ansible で mysql_usre を使えるように
- name: dest ~/.my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600
  when: mysql_root_password.stat.exists == false

- name: delete tmp.my.cnf
  file:
    path: /root/.tmp.my.cnf
    state: absent
