# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos6.8"
  config.vm.box_url = "https://github.com/CommanderK5/packer-centos-template/releases/download/0.6.8/vagrant-centos-6.8.box"


  # config.vm.network "public_network", bridge: 'en1: Wi-Fi (AirPort)'
  config.vm.network "private_network", ip: "192.168.34.11"
  # config.vm.network "public_network", ip: "192.168.34.20"
  config.vm.synced_folder "../app/", "/var/www/app"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "kingdom"
    vb.memory = 2048
    vb.cpus = 2

    # 時間をhostと同期
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 0]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "../ansible/playbook.yml"
    ansible.inventory_path = "../ansible/inventory/local"
  end

  config.vm.provision "shell", privileged: false, inline: <<-shell
    cd /var/www/app/script && ./composer.phar install
    cd /var/www/app/app && ./composer.phar install
    cd /var/www/app && STAGE=local php ./script/index.php db init
  shell
end
