stage: "{{ stage_local }}"
stage_user: vagrant

timeout: 5

ssl_directory: /etc/nginx/certs
ssl_private_key: "{{ ssl_directory }}/private.key"
ssl_csr: "{{ ssl_directory }}/server.csr"
ssl_public_key: "{{ ssl_directory }}/server.crt"

# log directory
mysql_log_directory: "{{ log_directory }}/mysql"
nginx_log_directory: "{{ log_directory }}/nginx"
php_log_directory: "{{ log_directory }}/php"

# mysql root password
database_root_password: jTf3dQ)ezU

databases:
  - name: kingdom
    user: kingdom
    password: 1234

# opcache
opcache_validate_timestamps: On
opcache_revalidate_freq: 0

# fpm
phpfpm_min_children: 5
phpfpm_max_children: 10
phpfpm_max_requests: 50
