- name: create log directory
  file:
    path: "{{ nginx_log_directory }}"
    state: directory
    owner: nginx
    group: "{{ stage_user }}"
    mode: 0755

- name: put log rotate file
  template:
    src: rotate.j2
    dest: /etc/logrotate.d/nginx
    mode: 0600
    backup: yes
