- name: install nginx rpm
  yum:
    name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    state: present

- name: install nginx
  yum:
    name: nginx
    enablerepo: nginx

- name: put nginx.conf
  template:
    src: templates/nginx-{{ stage }}.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
