- name: install modules for build phalcon
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - pcre-devel
    - gcc
    - make
    - git
    - re2c
    - unzip

- name: copy cphalcon source
  unarchive:
    src: cphalcon-3.2.0.tar.gz
    dest: /root/
  register: cphalcon_change

- name: install cphalcon
  shell: ./install
  args:
    chdir: /root/cphalcon-3.2.0/build
  when: cphalcon_change.changed

- name: put phalcon.ini
  template:
    src: phalcon.ini.j2
    dest: /etc/php.d/my-phalcon.ini
