- name: install remi rpm
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    state: present

- name: install modules for php
  yum:
    name: "{{ item }}"
    enablerepo: epel
    disablerepo: amzn-main
  with_items:
    - libwebp

- name: install php modules
  yum:
    name: "{{ item }}"
  with_items:
    - httpd
    - autoconf
    - automake
    - gd-last
    - libmcrypt
    - libtool-ltdl

- name: install php modules
  yum:
    name: "{{ item }}"
    enablerepo: remi-php71
    disablerepo: amzn-main
  with_items:
    - php
    - php-devel
    - php-pdo
    - php-mbstring
    - php-gd
    - php-xml
    - php-pecl-apcu
    - php-mysqlnd
    - php-soap
    - php-mcrypt
    - php-pecl-redis
    - php-pecl-yaml
    - php-opcache
    - php-fpm
